name: push-openapi-to-postman
description: 'Reads a JSON OpenAPI definition from your repo and pushes it to an existing Postman API, creating a new version on it'
author: David Espí Hernández <david.espi@postman.com>
branding:
  icon: arrow-up-circle
  color: blue
inputs:
  postman-api-key:
    description: 'Postman API Key'
    required: true
    default: ''
  path-to-definition:
    description: 'Path to the OpenAPI definition file in the repository'
    required: true
    default: './openAPI.json'
  aspec-id:
    description: 'Postman Spec ID'
    required: true
    default: 'String'
  api-path-to-file-name:
    description: 'The path and file name on the API where the definition should be updated'
    required: true
    default: 'index.json'
outputs:
  specId:
    description: 'The Spec ID'
runs:
  using: 'node16'
  main: 'dist/index.js'
